//lista blogs
GET http://localhost:3003/api/blogs


################################
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "New Age",
  "author": "Stream",
  "url": "www.example.com",
  "likes": 32
}

################################
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "author": "EA games",
  "url": "www.deadspace.com",
  "likes": 7788956
}

################################
GET http://localhost:3003/api/blogs/64c47d5ac8771ed399a44d1c

##############################
// Lista usuarios
GET http://localhost:3003/api/users/


##############################

POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username":"Remplex",
  "password":"123456",
  "name":"Stevenz"
}

################################

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Bioschock",
  "author": "Irrational Games (2kgames)",
  "url": "www.Bioshock.com",
  "likes": 7788956145111515,
  "userId": "64eea4a8fe72984c81945a11"
}

################################
//consiguiendo un blog especifico
GET http://localhost:3003/api/blogs/64f7ea5bc750432089958f91

################################

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Test",
  "author": "testing Local",
  "url": "www.localpost.com",
  "likes": 8888888,
  "userId": "64eea406fe72984c81945a0a"
}
################################
//consiguiendo un usuario especifico
GET http://localhost:3003/api/users/64eea406fe72984c81945a0a

################################
//login
POST http://localhost:3003/api/login 
Content-Type: application/json

{
  "username":"Remplex",
  "password":"123456"
}

################################
//post with user Stevenz
//token -> beared eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlbXBsZXgiLCJpZCI6IjY0ZWVhNGE4ZmU3Mjk4NGM4MTk0NWExMSIsImlhdCI6MTY5MzYyMDg2NH0.DcgD2XvDOnLpLaYjGddYv_Qr0VZwIj7sZzECNfH9HHg
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlbXBsZXgiLCJpZCI6IjY0ZWVhNGE4ZmU3Mjk4NGM4MTk0NWExMSIsImlhdCI6MTY5Mzk3MDczNCwiZXhwIjoxNjkzOTc0MzM0fQ.iibIJmWT94eUx64M2Ok0ZbEkKSmgDeM5CFV-HF38fmc

{
  "title": "im Test with login remplex and middleware",
  "author": "testing Local",
  "url": "www.localpost.com",
  "likes": 22222222222,
  "userId": "64eea4a8fe72984c81945a11"
}

################################

DELETE http://localhost:3003/api/blogs/64f7f1ca2726561e4a7fc007
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlbXBsZXgiLCJpZCI6IjY0ZWVhNGE4ZmU3Mjk4NGM4MTk0NWExMSIsImlhdCI6MTY5Mzk3MDczNCwiZXhwIjoxNjkzOTc0MzM0fQ.iibIJmWT94eUx64M2Ok0ZbEkKSmgDeM5CFV-HF38fmc

{
  "title": "im Test with login remplex and middleware",
  "author": "testing Local",
  "url": "www.localpost.com",
  "likes": 22222222222,
  "userId": "64eea4a8fe72984c81945a11"
}